---
server_id: "70e47899-7fb3-4ca6-b360-e0c0d1d6aa9e"

amqp:
  protocol: "amqp"
  user: "guest"
  password: "guest"
  host: "127.0.0.1"
  port: 5672

db:
  cloud:
    user: ""
    password: ""
    host: "127.0.0.1"
    port: 5432
    database: ""
  sensor:
    host: "127.0.0.1"
    port: 8086
    username: ""
    password: ""

log:
  log_file: ../../cmd/gocloudserver/gocloudserver.log
  log_level: debug
